# Generated by Django 6.0.1 on 2026-01-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
